name: Secret Scanning
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Secret Scanning - TruffleHog
        id: trufflehog
        uses: trufflesecurity/trufflehog@main
        continue-on-error: true
        with:
          path: ./
          base: "${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || '' }}"
          head: "${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || '' }}"
          extra_args: --results=verified --debug
      - name: Scan Results Status
        if: steps.trufflehog.outcome == 'failure'
        run: exit 1
