name: Secret Scanning

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write
  security-events: write

jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Secret Scanning - TruffleHog
        id: trufflehog
        uses: trufflesecurity/trufflehog@main
        continue-on-error: true
        with:
          path: ./
          base: "${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || '' }}"
          head: "${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || '' }}"
          extra_args: --debug

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: trufflehog.sarif

      - name: Scan Results Status
        if: steps.trufflehog.outcome == 'failure'
        run: exit 1
